TEXT_GAMEOVER    = "GAME OVER";
TEXT_CONGRATS    = "CONGRATULATIONS";
TEXT_PLAY        = "PLAY";
TEXT_SCORE       = "SCORE";
TEXT_LEVEL       = "LEVEL";
TEXT_FINAL_SCORE = "FINAL SCORE";
TEXT_SELECT_LEVEL = "SELECT A LEVEL";
TEXT_DELETE_SAVINGS = "ALL YOUR PROGRESS WILL BE CANCELLED! ARE YOU SURE?";
TEXT_NO = "NO";
TEXT_YES = "YES";
TEXT_CREDITS_DEVELOPED = "DEVELOPED BY";
TEXT_LINK1 = "www.codethislab.com";

TEXT_SHARE_IMAGE = "200x200.jpg";
TEXT_SHARE_TITLE = "Congratulations!";
TEXT_SHARE_MSG1 = "You collected <strong>";
TEXT_SHARE_MSG2 = " points</strong>!<br><br>Share your score with your friends!";
TEXT_SHARE_SHARE1 = "My score is ";
TEXT_SHARE_SHARE2 = " points! Can you do better";